# Generated by Django 2.0 on 2018-03-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsign', '0002_auto_20180327_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
