# Generated by Django 2.0 on 2018-03-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logsign', '0003_auto_20180327_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated',
        ),
    ]
